name = "Create: Astral | Midlighted"
author = "Ivy"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a68ee309ca33e041c9689acd179229095eac61139cbe3f1585b8b1940d4fd055"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"

[options]
no-internal-hashes = true
