name = "Create: Astral | Midlighted"
author = "Ivy"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "735afba95c26ce2c9c872f62eea43e44659819a550728bd68e7587a98f4acc77"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
