name = "Create: Astral | Midlighted"
author = "Ivy"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5754d7038c6c16caf360dafcf600e6dac78d84bbceb0c8cc889f2461b1baf1db"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
