name = "Create: Astral | Midlighted"
author = "Ivy"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e67b295579051250ed21d9edbcb6d8e338b19d8685bf72e36cacef65f717fd3"

[versions]
fabric = "0.14.14"
minecraft = "1.18.2"
